services:
  reportr:
    image: ghcr.io/regutierrez/sbs-reportr:latest
    container_name: reportr
    expose:
      - "9999"
    environment:
      REPORTR_DATA_ROOT: ${REPORTR_DATA_ROOT:-/tmp/reportr}
    volumes:
      - frontend_dist:/srv/frontend
      - reportr_data:${REPORTR_DATA_ROOT:-/tmp/reportr}
    networks:
      edge:
        aliases:
          - reportr
    restart: unless-stopped

volumes:
  frontend_dist:
  reportr_data:

networks:
  edge:
    external: true
